### ISSUE TITLE
Integrate Kiali Core UI library into OSSMC plugin

### ISSUE THREAD

**Issue by ferhoyos** [kiali/openshift-servicemesh-plugin#110]
New Kiali UI core library is created with reusable kiali components, types and endpoints. As part of #109 effort, OSSMC will use such library to render kiali components in native.

Actions to perform the library integration:
- Add core-ui library reference to package.json
- Add script to link local core ui library code into OSSMC plugin (only for development)
- Add docs to describe the link process

**Comment by aljesusg** [comment]
About docs and script I would do them in the library not the plugin

**Comment by ferhoyos** [comment]
If you place the script in the library, how do you know which application you have to link the library? Passing the application folder as an argument of the script?

**Comment by aljesusg** [comment]
The point is how to work with the library not how to work with the plugin. 

It makes no sense create this in all places where we are going to use the library.

I would do a doc like README with the steps instead a script.

**Comment by ferhoyos** [comment]
Closing the ticket since core UI development setup is documented on https://github.com/kiali/core-ui
