### ISSUE TITLE
Improve IstioConfigList page in console plugin

### ISSUE THREAD

**Issue by ferhoyos** [kiali/openshift-servicemesh-plugin#117]
Epic https://github.com/kiali/openshift-servicemesh-plugin/issues/109

Currently IstioConfigList within OSSMC is a simpler version of what is provided in kiali upstream. One example are configuration validations:

OSSMC:
![image](https://user-images.githubusercontent.com/122779323/227200206-aaaa20b1-fb9a-4487-a16b-66f956449f88.png)

Kiali:
![image](https://user-images.githubusercontent.com/122779323/227200294-d9a1e341-c38f-465f-8c76-06265b755211.png)

IstioConfigList should provide the same information as Kiali upstream:
- Replace Configuration text value with status icon
- Add namespace badge

Besides namespace link to its detail information page could be added. This feature would be only available at the console (Kiali does not have namespace detail page).

**Comment by jshaughn** [comment]
What does it mean to be "more aligned with upstream"?  The plugins should conform as best as possible to Console, and so in general I think the native plugins should move in that direction, and upstream perhaps should conform more to downstream.  If nothing else, please as @hhovsepy about why there may currently be a difference.

**Comment by hhovsepy** [comment]
The current difference is because we did not want to copy the status icon component to cluster plugin code, leaved for the time when separate Kiali UI components will be created and reused in plugin.

**Comment by ferhoyos** [comment]
Maybe the title is a bit confusing here. What "more aligned with upstream" means is to provide same information as upstream, but maintaining as much as possible the look and feel of the console. The status icon provides more information than just a 'Valid' message (for example to show if the istio object is reconciled or not) and it conforms with the console. 

On any case we have to check first if there is a console component that can be used instead of Kiali one that provides similar information (for example ResourceLinks are used instead of PFBadges for Name and Namespaces columns). In case there is not such component then we have to use Kiali one and maybe adapt its look and feel to make it conform as much as possible with the console (like the status icon).

**Comment by ferhoyos** [comment]
Closing since parent epic https://github.com/kiali/openshift-servicemesh-plugin/issues/109 is closed
