### ISSUE TITLE
Prefix css in all styles

### ISSUE THREAD

**Issue by aljesusg** [kiali/openshift-servicemesh-plugin#138]
There is a way to set a prefix css in the components. We need to migrate all components to use this and add it to the guidelines

```ts
import { getKialiStyle } from '../../utils/StyleUtils';

const validationStyle = getKialiStyle({
  textAlign: 'left',
  $nest: {
    '&:last-child p': {
      margin: 0
    }
  }
});
```

Related with https://github.com/kiali/openshift-servicemesh-plugin/issues/109

**Comment by ferhoyos** [comment]
Closing since parent epic https://github.com/kiali/openshift-servicemesh-plugin/issues/109 is closed
