### ISSUE TITLE
After updating spec.kiali.url attribute in OSSMConsole the OpenShift Console still calls`kialia-istio-system.<default_route>`

### ISSUE THREAD

**Issue by Spitfire1900** [kiali/openshift-servicemesh-plugin#186]
Using OpenShift Service Mesh Console 0.3.0 on OpenShift 4.11.27.

I have an OSSM installation deployed with a non-default name of `ossm` in an `ossm-sand` namespace instead of `istio-system`. This means that the Route URL for Kiali is at `kiali-ossm-sand.<default_route>` instead of `kiali-istio-system.<default_route>`.

However, even after updating the OSSMConsole spec to the appropriate URL and cycling the `ossmconsole` and `ossmconsole-operator` Deployments, when navigating to Service Mesh panes in the OpenShift Console the callback is still going to `kiali-istio-system.<default_route>` instead of `kiali-ossm-sand.<default_route>`, and `kiali-ossm-sand.<default_route>and `https://console-openshift-console.apps.sand.openshift.localhost/api/plugins/ossmconsole/plugin-config.json` is returning `kiali-istio-system.<default_route>` likewise.

**Comment by Spitfire1900** [comment]
I have validated that the associated `plugin-conf` ConfigMap was updated correctly, still reproducing.

**Comment by jmazzitelli** [comment]
0.3.0 is old (even though its the latest published). The latest stuff won't use the Route URL... it will only rely on the service info. We are looking to release a new 0.4.0 in the near future. In the meantime, you can try to build it yourself and try from main branch and see if it helps fix your issue. The README should be able to help: https://github.com/kiali/openshift-servicemesh-plugin#how-to-run-the-plugin-for-local-development

**Comment by jmazzitelli** [comment]
0.4.0 has been released.

**Comment by Spitfire1900** [comment]
Testing 0.4.0 lead to creation of #215
