### ISSUE TITLE
Error 500 in Traces tab

### ISSUE THREAD

**Issue by josunect** [kiali/openshift-servicemesh-plugin#188]
Navigating to the Traces tab into a Workload/Deployment/Services, you receive a 500 error: 

Mesh tabs: 
![image](https://github.com/kiali/openshift-servicemesh-plugin/assets/49480155/7a0454a3-e421-4a15-9a07-6b7b0c5d4218)

Traces: 
![image](https://github.com/kiali/openshift-servicemesh-plugin/assets/49480155/624641e2-8170-4887-b46e-652932ed5231)

Request: 

http://localhost:3000/api/stats/metrics
`{"queries":[{"queryTime":1690271198,"target":{"namespace":"bookinfo","name":"details","kind":"service"},"interval":"1h","direction":"inbound","avg":false,"quantiles":["0.75","0.9","0.99"]}]}: `

Response: 
```
{
    "error": "1 errors:\nNamespace 'bookinfo': OCP Cluster [] is not found or is not accessible for Kiali"
}
```

Tested in crc 2.20

Ref. https://github.com/kiali/kiali/issues/6405

**Comment by hhovsepy** [comment]
It seems whole metrics regression:
![Screenshot from 2023-07-25 09-59-02](https://github.com/kiali/openshift-servicemesh-plugin/assets/604313/5f872119-7ea3-4da7-a4f8-33df01040c69)

**Comment by josunect** [comment]
> It seems whole metrics regression: ![Screenshot from 2023-07-25 09-59-02](https://user-images.githubusercontent.com/604313/255831602-5f872119-7ea3-4da7-a4f8-33df01040c69.png)

Thank you, @hhovsepy 
I think then it should be reviewed in Kiali...
