### ISSUE TITLE
plugin needs to know the kiali.url for the specific tenant it wants to observe

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/openshift-servicemesh-plugin#28]
When only one Kiali is installed in the cluster (i.e. there is no multi-tenancy - all namespaces in the cluster are accessible to a single instance of Kiali), then the plugin can use the kiali.url setting that the user provided in the OSSMPlugin CR (when left empty, the operator will set this for the user - which will be the typical use case). This means the one Kiali route instance will be where that kiali.url setting points to.

However, this breaks down in multi-tenant scenarios. There isn't just one kiali.url the plugin needs to know about. Based on what namespace the plugin wants to observe, it has to figure out which Kiali route URL to talk to.

This is relatively easy to accomplish because the Kiali operator adds a label to all accessible namespaces - `kiali.io/member-of`. The value of that namespace label will be the name of the control plane of the namespace's tenant - and that control plane is where the Kiali route can be found.

So, for example, if I have an application deployed in the `alpha` namespace and that namespace is part of a tenant controlled by that tenant's control plane, this is how we can find out which Kiali is observing that tenant:

(note: I am using Bash commands here, but obviously, this is just pseudo-code - we'd have to do this in the plugin javascript or other code such as that, rather than rely on Bash)

First, get the label to find out which control plane namespace where the observing kiali lives in:

```bash
KIALI_NAMESPACE="$(oc get namespace alpha -o jsonpath="{.metadata.labels['kiali\.io/member-of']}")"
```

Now that we know the control plane namespace, we know where the observing Kiali lives (it is in that control plane namespace itself). Thus, we just look in that namespace for the Route (the control plane namespace is where the Kiali routes lives, too):

```bash
KIALI_ROUTE="https://$(oc get routes -n ${KIALI_NAMESPACE} -l app.kubernetes.io/name=kiali -o jsonpath="{.items[0].spec.host}")"
```

The $KIALI_ROUTE is now the kiali.url that the plugin should use - that is the Kiali that the plugin should be talking to when looking at workloads within that namespace.

The OSSM Plugin CR also has `serviceName`, `serviceNamespace`, and `servicePort` in its `kiali` section, but all of those can be obtained from the route that is auto-discovered:

```bash
SERVICE_NAME="$(oc get route -n ${KIALI_NAMESPACE} -l app.kubernetes.io/name=kiali -o jsonpath={.items[0].spec.to.name})"
SERVICE_NAMESPACE="${KIALI_NAMESPACE}"
SERVICE_PORT="$(oc get route -n ${KIALI_NAMESPACE} -l app.kubernetes.io/name=kiali -o jsonpath={.items[0].spec.port.targetPort})"
```

_(NOTE: This assumes the web root context for Kiali is "/" (which is the default on OpenShift)... but this is assumed in the plugin/plugin operator today anyway. If we want to support custom web root context paths (like `/kiali` which is the default for non-OpenShift clusters) then we'd have to do additional look ups in the kiali config to determine the context path. But for now, ignore that.)_

**Comment by ferhoyos** [comment]
Closing the issue since kiali.url is not used anymore with the removal of iframes.
