### ISSUE TITLE
Traffic graph context menu options do not redirect to the correct pages

### ISSUE THREAD

**Issue by ferhoyos** [kiali/openshift-servicemesh-plugin#284]
### Describe the bug

Every node in the traffic graph has a context menu containing links to specific pages for that node (details, traffic, logs, etc.). However, none of the links redirect to the correct page within the OpenShift console.

![image](https://github.com/kiali/openshift-servicemesh-plugin/assets/122779323/05c074ca-6c83-419d-a806-ca7a76294cf3)

### Expected Behavior

Each link in the context menu's node should redirect to correct page for that node.

### What are the steps to reproduce this bug?

1. Go to the traffic graph page
2. Click on the context menu of any node
3. Select any of the link options
4. Check that nothing happens

### Environment

- **OSSMC/Kiali version:** 1.73
- **OpenShift version:** 4.13
- **Istio version:** 1.18

**Comment by jshaughn** [comment]
This should be backported to v1.73 for OSSM 2.5.x.
