### ISSUE TITLE
OSSMC does not show Istio Config names 

### ISSUE THREAD

**Issue by ScriptingShrimp** [kiali/openshift-servicemesh-plugin#331]
OSSMC (left) does not show Istio Config names as standalone Kiali (right)

OpenShift version 4.15.18
Kiali Community Operator 1.86.0 provided by Kiali
istiod Version: 1.22.1
Namespace: istio-system

![Screenshot from 2024-07-02 17-18-05](https://github.com/kiali/openshift-servicemesh-plugin/assets/86114326/6f385225-fc1d-420f-bd5b-c1e2238b2991)

**Comment by ferhoyos** [comment]
I cannot reproduce the issue with the latest version of OSSMC. Could you check again please?

**Comment by ScriptingShrimp** [comment]
cannot reproduce, closing
