### ISSUE TITLE
OSSMConsole autofilled a non-existent image

### ISSUE THREAD

**Issue by mattzech** [kiali/openshift-servicemesh-plugin#346]
### Describe the bug

**This has now been fixed but I just want to bring it to your attention**
Every week, we rebuild our development clusters which teams use as a testing environment before moving to staging and prod.
The following OSSM CR has been successfully applied after the rebuild with no issues until a few weeks ago:
```yaml
apiVersion: kiali.io/v1alpha1
kind: OSSMConsole
metadata:
  name: ossmconsole
  namespace: istio-system
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
```

During the problem week (July 15th), the OSSMConsole created the pod manifest correctly, but the image it was trying to use was `quay.io/kiali/ossmconsole:v1.87.0`. Looking at the quay repo, this image did not exist at the time. This caused many failed image pulls which actually led to customers reporting the clusters unusable due to api slowness. We had to remove the OSSMConsole resource from the cluster to improve performance. 

Could you provide me with details on how this CR decides which image to use? I assume it has something to do with the Kiali version being referenced. Before we re-apply this resource back to the cluster, we need a way to confirm that this non-existent image issue will not happen again.

Thank you!

### Expected Behavior

OSSMConsole creates pod which pulls from existing image in the quay repo

### What are the steps to reproduce this bug?

N/A

### Environment

Remember that OSSMC must match Kiali version. Learn about how to determine Kiali version [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).

- **OSSMC/Kiali version:** 1.87
- **OpenShift version:** 4.14.31
- **Istio version:**
- **Other notable environmental factors:**

**Comment by ferhoyos** [comment]
Hi @mattzech,

yes, there were some issues with OSSMC v1.87 that delayed the release (https://www.github.com/kiali/openshift-servicemesh-plugin/pull/334).

Note that OSSMC is based on Kiali code, so it has to wait for Kiali to be released before the OSSMC release. This is the standard schedule during release weeks:
- **Monday:** Kiali and Kiali operator are released
- **Tuesday:** OSSMC is released

Therefore, you can expect a one-day gap between the Kiali operator release and the OSSMC release. This delay can be longer if there is some issue with OSSMC release, although this is not very common. You can check if the latest OSSMC version is released on the OSSMC releases page (https://github.com/kiali/openshift-servicemesh-plugin/releases)

> Could you provide me with details on how this CR decides which image to use?

If you do not specify an image version, the OSSMConsole CR installs the same version as the Kiali operator (in your case, v1.87). A specific image version can be installed using the `spec.deployment.imageVersion` field of the CR.

https://kiali.io/docs/configuration/ossmconsoles.kiali.io/#.spec.deployment.imageVersion
