### ISSUE TITLE
Plugin service actions on details pages

### ISSUE THREAD

**Issue by lucasponce** [kiali/openshift-servicemesh-plugin#43]
A similar situation like https://github.com/kiali/openshift-servicemesh-plugin/issues/42 happens with the Kiali Service actions.

Kiali has the "actions" dropdown in the shared area:
![image](https://user-images.githubusercontent.com/1662329/177535731-e048fe2f-4ef4-4905-841f-a515fbef1c5a.png)

But these actions have been omitted under the plugin context to not overlap with the service actions located in the common area of the OpenShift Console:
![image](https://user-images.githubusercontent.com/1662329/177536026-f89ce052-940f-4e88-ab88-6856ea01e489.png)

This issue should discuss with @andrew-ronaldson which should be the best place to locate them under the plugin context.

One possibility could be to add them as regular "Kubernetes Actions" but perhaps that may populate a long list of actions there and be less visible/useful to the user. Another option could be to also to use the "minigraph" kebap to place specific actions on the "Service Mesh" tab, then we can reduce the number of "where to find the right actions for the service mesh" possibilities.

![image](https://user-images.githubusercontent.com/1662329/177536470-3289e628-987d-4d7f-ae7e-bd782695106a.png)

Also, technically speaking, using the "minigraph kebap" to locate these actions simplifies the implementation, adding them at the OpenShift Console level would require a re-implementation of that logic in the plugin (not discarded, but in terms of timeline it's also something to consider).

**Comment by andrew-ronaldson** [comment]
I think that this could stay as the minigraph kebab actions menu. It is specific to the contents of the service mesh tab so having it on the OCP actions level might confuse people without any context.
