### ISSUE TITLE
Add Kiali validations on Istio Detail pages 

### ISSUE THREAD

**Issue by lucasponce** [kiali/openshift-servicemesh-plugin#52]
In the current state of the plugin, the Istio "details" page is not implemented by the plugin, it's redirected to the standard page that OpenShift Console uses to visualize and edit any resource.

~~The ideal situation would be that the "dynamic-plugin-sdk" allow adding new tabs where additional "Service Mesh" information (like validations) can be added, but it seems this "extension point" is not yet available.~~

Then, the plugin should provide an implementation of a similar page that would allow augmenting the information with the Kiali validations, plus the standard edition features on the resource.

**Comment by lucasponce** [comment]
Note, that now the plugin can add "Service Mesh" tab to Istio resources in a native way:
![image](https://user-images.githubusercontent.com/1662329/183883671-de25f9b3-1750-42b4-b189-f48b5666224c.png)

This issue can be used to design how to implement the "Service Mesh" tab at this level. 

One initial suggestion could be to delegate the CRUD capabilities to the original Openshift page, and the "Service Mesh" tab can query Kiali to collect the validations and show an editor with the validations in-line the sidepanel that Kiali standalone offers.

I think that adding new side panels to the original YAML editor is not yet available in the "dynamic-plugin-sdk".

**Comment by hhovsepy** [comment]
Added Istio config details page in kiosk mode as read only YAML editor with validations in an iFrame contant:
![Screenshot from 2022-11-16 12-05-13](https://user-images.githubusercontent.com/604313/203630671-b1bde573-b5b0-4e75-ba6f-c698ea712690.png)
