### ISSUE TITLE
Add internationalization support

### ISSUE THREAD

**Issue by lucasponce** [kiali/openshift-servicemesh-plugin#60]
The Kiali standalone project hasn't introduced i18 support.
But OpenShift Console has support, and at some point in the plugin lifecycle, this topic should come to the backlog.

Here the recommended approach would be to take a look at what other plugins are doing:
https://github.com/kubevirt-ui/kubevirt-plugin/blob/main/INTERNATIONALIZATION.md

Also, this topic is different for Kiali as in these first steps; this plugin uses a mix of approaches to reuse the Kiali standalone UI plus adding native pages using the dynamic plugin SDK.

**Comment by ferhoyos** [comment]
Not applicable since internationalization support is going to be implemented in [#kiali/kiali](https://github.com/kiali/kiali)
