### ISSUE TITLE
[dev] instructions for running locally does not work

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/openshift-servicemesh-plugin#73]
I'm trying to follow these instructions: https://github.com/kiali/openshift-servicemesh-plugin#how-to-run-the-plugin-for-local-development

Both commands work and I see things running on ports 9000 (the plugin) and 9001 (the console) and I see the console in my browser.

However, the plugin is not visible in the console.

I see these errors in the console logs.

First I see a bunch of these:

```
2022/08/31 13:16:44 CheckOrigin: Proxy has no configured Origin. Allowing origin [http://localhost:9000] to wss://api....my-url-here....com:6443/apis/config.openshift.io/v1/clusterversions?watch=true&fieldSelector=metadata.name%3Dversion
```

Then this:

```
E0831 13:14:30.320303       1 handlers.go:165] GET request for "ossmconsole" plugin failed: Get "http://host.containers.internal:9001/plugin-manifest.json": dial tcp 172.17.0.1:9001: connect: connection refused
```

So something else is missing in the instructions because there seems to be a step that I need to do in order to get this to work.

**Comment by jmazzitelli** [comment]
I thought maybe this would fix it (and I have a feeling we will still need this), but it still doesn't work when I do this:

```diff
diff --git a/plugin/plugin-config.json b/plugin/plugin-config.json
index 42a5276..9998e25 100644
--- a/plugin/plugin-config.json
+++ b/plugin/plugin-config.json
@@ -1,3 +1,6 @@
 {
-  "kialiUrl": "https://kiali-istio-system.apps-crc.testing"
-}
\ No newline at end of file
+  "kialiUrl": "https://kiali-istio-system.apps-crc.testing",
+  "serviceName": "kiali",
+  "serviceNamespace": "istio-system",
+  "servicePort": "20001"
+}
```

**Comment by josunect** [comment]
I've have it running following the next steps:

- cd plugin
- yarn install
- cp plugin-config.json dist

Edited dist/plugin-config.json:

```
{
  "kialiUrl": "http://localhost:3000"
}
```

- yarn run start
- cd plugin
- yarn run start-console

![image](https://user-images.githubusercontent.com/49480155/187693074-2aa55835-e58d-48b2-aef7-ea16c49a1d31.png)

I can see  the following messages in the console: 

`2022/08/31 13:40:22 CheckOrigin: Proxy has no configured Origin. Allowing origin [http://localhost:9000] to wss://api.crc.testing:6443/api/v1/events?watch=true&resourceVersion=124280`

**Comment by jmazzitelli** [comment]
Oh!

>  "kialiUrl": "http://localhost:3000"

You are running Kiali locally, too (with run-kiali.sh, I assume)

THAT isn't in the instructions :) 

I thought we could proxy to the kiali that is running inside the cluster. I though that is how @lucasponce and @hhovsepy ran their environment.

**Comment by hhovsepy** [comment]
yes, we were using the Kiali running on crc cluster, and that kiali could be deployed from local git branch as well, by running "make clean build-ui build cluster-push operator-create kiali-create"

**Comment by josunect** [comment]
> yes, we were using the Kiali running on crc cluster, and that kiali could be deployed from local git branch as well, by running "make clean build-ui build cluster-push operator-create kiali-create"

Ah! I wonder, how your plugin-config.json looks like?

**Comment by jmazzitelli** [comment]
OK, so @josunect got it to run when Kiali is deployed locally, and @hhovsepy got it to run when Kiali is deployed inside the cluster but that cluster is also running on his local machine. I fail when Kiali is deployed in a remote cluster. So I have a feeling this won't work when Kiali is found on a different network.

I wonder if I can get this to work with a port-forward. I'll try that next.

**Comment by jmazzitelli** [comment]
I can't get this to work with a port-forward either.
