### ISSUE TITLE
Dark theme is not propagated to iframe pages

### ISSUE THREAD

**Issue by nrfox** [kiali/openshift-servicemesh-plugin#80]
Pages that are using iframes do not have the theme selected in console propagated. The istio config page correctly renders with the dark mode theme.

Istio config:
![Screenshot from 2022-09-09 12-42-03](https://user-images.githubusercontent.com/6226732/189399852-c335a188-a9d1-4597-b99f-4c106dbb903a.png)

Graph:
![Screenshot from 2022-09-09 12-41-56](https://user-images.githubusercontent.com/6226732/189399853-14df37c8-131f-4301-b913-06e6691f3ed5.png)

Overview:
![Screenshot from 2022-09-09 12-41-48](https://user-images.githubusercontent.com/6226732/189399855-ef479b94-078e-43fc-ba97-130f43ecc104.png)

**Comment by nrfox** [comment]
Probably most pronounced on the workloads --> service mesh tab where the top level of tabs is one color and the bottom level is another:
![Screenshot from 2022-09-09 12-58-46](https://user-images.githubusercontent.com/6226732/189402881-4982d6ff-7f25-489e-b965-5f5b73650d8c.png)

**Comment by jshaughn** [comment]
That's a tough one for plugins, especially i-framed, that don't support a dark mode.

**Comment by ferhoyos** [comment]
Not applicable since iframes are going to be removed and dark mode implemented in [#kiali/kiali](https://github.com/kiali/kiali)
